### ISSUE TITLE
FRONT - Crear componente modal para las acciones de "Crear" y "Agregar"

### ISSUE THREAD

**Issue by renatosalas** [ISC-ITESM-GDA/labweb-ad16#28]

**Comment by Robfz** [comment]
Renato, para qué vistas tienes planeado hacer el modal?

**Comment by renatosalas** [comment]
Quiero hacer uno genérico utilizando vue-strap

**Comment by renatosalas** [comment]
Acabo de hacer push a una nueva branch "generic_modal", en la cual coloque el template para generar un modal utilizando vue-strap; npm install previo. 
Un dato a destacar que para el manejo de la visibilidad del modal utilizo una variable "showAddModal", la cual cuando es true muestra el modal
