### ISSUE TITLE
User settings view

### ISSUE THREAD

**Issue by Robfz** [ISC-ITESM-GDA/labweb-ad16#40]
User settings:
As a user I want to have a section where I am able to change my user information, manage payment and logout.

AC:
- There is a payment section
- I can pay for the service via PayPal or some other provider
- User information is shown (name, profile picture, role)
- User information can be updated (name, profile picture, role)
- Logout button
- This is the first page shown when user logs in

**Comment by DiegoNoe** [comment]
Renato y yo implementamos subscripción a Openpay.
